# Generated by Django 6.0.1 on 2026-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tune_type', models.CharField(choices=[('N/A', 'N/A'), ('Jig', 'Jig'), ('Reel', 'Reel'), ('Polka', 'Polka'), ('Listening Tune', 'Listening_Tune')], max_length=25)),
                ('file', models.FileField(upload_to='songs/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
