# Generated by Django 6.0.1 on 2026-01-28 09:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCBSite', '0002_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('content_text', models.TextField(blank=True)),
                ('image_file', models.ImageField(upload_to='images/')),
                ('article_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-article_created_at'],
            },
        ),
    ]
