# Generated by Django 6.0.1 on 2026-01-28 14:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCBSite', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
