# Generated by Django 6.0.1 on 2026-01-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCBSite', '0004_events_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.URLField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['link_name'],
            },
        ),
    ]
