# Generated by Django 6.0.1 on 2026-02-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCBSite', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='songs',
            name='tune_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Jig', 'Jig'), ('Slip Jig', 'Slip_Jig'), ('Reel', 'Reel'), ('Polka', 'Polka'), ('Hornpipe', 'Hornpipe'), ('Listening Tune', 'Listening_Tune')], max_length=25),
        ),
    ]
